//! Flow on manifold: vector field generating agent dynamics.
//!
//! A flow φᵗ: M → M is a one-parameter group of diffeomorphisms on a manifold M,
//! generated by a vector field V: M → TM. Agent state evolves via dx/dt = V(x).

use nalgebra::{DVector, DMatrix};
use serde::{Serialize, Deserialize};

/// A vector field on an n-dimensional manifold.
/// Maps a point to its velocity vector (tangent vector).
pub trait VectorField: Send + Sync {
    /// Dimension of the manifold.
    fn dim(&self) -> usize;

    /// Evaluate the vector field at point x: V(x).
    fn evaluate(&self, x: &DVector<f64>) -> DVector<f64>;

    /// Compute the Jacobian dV/dx numerically via finite differences.
    fn jacobian(&self, x: &DVector<f64>) -> DMatrix<f64> {
        let n = self.dim();
        let eps = 1e-7;
        let mut jac = DMatrix::zeros(n, n);
        for j in 0..n {
            let mut xp = x.clone();
            let mut xm = x.clone();
            xp[j] += eps;
            xm[j] -= eps;
            let vp = self.evaluate(&xp);
            let vm = self.evaluate(&xm);
            for i in 0..n {
                jac[(i, j)] = (vp[i] - vm[i]) / (2.0 * eps);
            }
        }
        jac
    }
}

/// A closure-based vector field for convenience.
pub struct FnVectorField {
    dim: usize,
    #[allow(clippy::type_complexity)]
    f: Box<dyn Fn(&DVector<f64>) -> DVector<f64> + Send + Sync>,
}

impl FnVectorField {
    pub fn new<F>(dim: usize, f: F) -> Self
    where
        F: Fn(&DVector<f64>) -> DVector<f64> + Send + Sync + 'static,
    {
        Self { dim, f: Box::new(f) }
    }
}

impl VectorField for FnVectorField {
    fn dim(&self) -> usize { self.dim }
    fn evaluate(&self, x: &DVector<f64>) -> DVector<f64> {
        (self.f)(x)
    }
}

/// Integration result from flowing a point.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlowResult {
    /// The final point after integration.
    pub endpoint: Vec<f64>,
    /// Full trajectory (optional).
    pub trajectory: Vec<Vec<f64>>,
    /// Times at each trajectory point.
    pub times: Vec<f64>,
}

/// RK4 integration step.
fn rk4_step(vf: &dyn VectorField, x: &DVector<f64>, dt: f64) -> DVector<f64> {
    let k1 = vf.evaluate(x);
    let k2 = vf.evaluate(&(x + &(k1.scale(dt / 2.0))));
    let k3 = vf.evaluate(&(x + &(k2.scale(dt / 2.0))));
    let k4 = vf.evaluate(&(x + &k3.scale(dt)));
    x + &(k1.scale(dt / 6.0) + &k2.scale(dt / 3.0) + &k3.scale(dt / 3.0) + &k4.scale(dt / 6.0))
}

/// Flow a point along the vector field for time t.
pub fn flow(
    vf: &dyn VectorField,
    x0: &DVector<f64>,
    t: f64,
    dt: f64,
    store_trajectory: bool,
) -> FlowResult {
    let steps = (t.abs() / dt).ceil() as usize;
    let actual_dt = t / steps as f64;
    let mut x = x0.clone();
    let mut trajectory = Vec::new();
    let mut times = vec![0.0];

    if store_trajectory {
        trajectory.push(x.iter().copied().collect());
    }

    for i in 1..=steps {
        x = rk4_step(vf, &x, actual_dt);
        if store_trajectory {
            trajectory.push(x.iter().copied().collect());
        }
        times.push(i as f64 * actual_dt);
    }

    FlowResult {
        endpoint: x.iter().copied().collect(),
        trajectory,
        times,
    }
}

/// Flow for a fixed number of steps (useful for discrete-time analysis).
pub fn flow_steps(
    vf: &dyn VectorField,
    x0: &DVector<f64>,
    steps: usize,
    dt: f64,
) -> DVector<f64> {
    let mut x = x0.clone();
    for _ in 0..steps {
        x = rk4_step(vf, &x, dt);
    }
    x
}

/// Divergence of a vector field at point x: ∇·V = Σ ∂Vᵢ/∂xᵢ
pub fn divergence(vf: &dyn VectorField, x: &DVector<f64>) -> f64 {
    let jac = vf.jacobian(x);
    (0..vf.dim()).map(|i| jac[(i, i)]).sum()
}

/// Curl (2D): ∂V₂/∂x₁ - ∂V₁/∂x₂. Only defined for 2D fields.
pub fn curl_2d(vf: &dyn VectorField, x: &DVector<f64>) -> f64 {
    assert_eq!(vf.dim(), 2, "Curl only defined for 2D vector fields");
    let jac = vf.jacobian(x);
    jac[(1, 0)] - jac[(0, 1)]
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_abs_diff_eq;

    #[test]
    fn test_constant_field() {
        let vf = FnVectorField::new(2, |x| DVector::from_vec(vec![1.0, 0.0]));
        let x0 = DVector::from_vec(vec![0.0, 0.0]);
        let result = flow(&vf, &x0, 1.0, 0.01, false);
        assert_abs_diff_eq!(result.endpoint[0], 1.0, epsilon = 1e-4);
        assert_abs_diff_eq!(result.endpoint[1], 0.0, epsilon = 1e-4);
    }

    #[test]
    fn test_linear_field() {
        // dx/dt = -x, dy/dt = -y  → x(t) = x₀ e^{-t}
        let vf = FnVectorField::new(2, |x| DVector::from_vec(vec![-x[0], -x[1]]));
        let x0 = DVector::from_vec(vec![1.0, 1.0]);
        let result = flow(&vf, &x0, 1.0, 0.01, false);
        let expected = (-1.0f64).exp();
        assert_abs_diff_eq!(result.endpoint[0], expected, epsilon = 1e-4);
        assert_abs_diff_eq!(result.endpoint[1], expected, epsilon = 1e-4);
    }

    #[test]
    fn test_trajectory_storage() {
        let vf = FnVectorField::new(1, |x| DVector::from_vec(vec![1.0]));
        let x0 = DVector::from_vec(vec![0.0]);
        let result = flow(&vf, &x0, 1.0, 0.1, true);
        assert_eq!(result.trajectory.len(), 11); // 0..=10
        assert_eq!(result.times.len(), 11);
    }

    #[test]
    fn test_negative_time() {
        let vf = FnVectorField::new(1, |x| DVector::from_vec(vec![1.0]));
        let x0 = DVector::from_vec(vec![5.0]);
        let result = flow(&vf, &x0, -2.0, 0.01, false);
        assert_abs_diff_eq!(result.endpoint[0], 3.0, epsilon = 1e-3);
    }

    #[test]
    fn test_jacobian_numerical() {
        let vf = FnVectorField::new(2, |x| DVector::from_vec(vec![-x[0], -2.0 * x[1]]));
        let x0 = DVector::from_vec(vec![1.0, 1.0]);
        let jac = vf.jacobian(&x0);
        assert_abs_diff_eq!(jac[(0, 0)], -1.0, epsilon = 1e-5);
        assert_abs_diff_eq!(jac[(1, 1)], -2.0, epsilon = 1e-5);
        assert_abs_diff_eq!(jac[(0, 1)], 0.0, epsilon = 1e-5);
    }

    #[test]
    fn test_divergence() {
        // V = (-x, -2y) → div = -3
        let vf = FnVectorField::new(2, |x| DVector::from_vec(vec![-x[0], -2.0 * x[1]]));
        let x0 = DVector::from_vec(vec![1.0, 1.0]);
        assert_abs_diff_eq!(divergence(&vf, &x0), -3.0, epsilon = 1e-5);
    }

    #[test]
    fn test_curl_2d() {
        // V = (-y, x) → curl = 1 - (-1) = 2
        let vf = FnVectorField::new(2, |x| DVector::from_vec(vec![-x[1], x[0]]));
        let x0 = DVector::from_vec(vec![1.0, 0.0]);
        assert_abs_diff_eq!(curl_2d(&vf, &x0), 2.0, epsilon = 1e-4);
    }

    #[test]
    fn test_flow_steps() {
        let vf = FnVectorField::new(1, |x| DVector::from_vec(vec![0.0]));
        let x0 = DVector::from_vec(vec![3.14]);
        let result = flow_steps(&vf, &x0, 100, 0.01);
        assert_abs_diff_eq!(result[0], 3.14, epsilon = 1e-10);
    }
}
